# Generated by Django 4.2.20 on 2025-05-29 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_thread_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='receiver',
            new_name='recipient',
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_read',
        ),
    ]
